apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://aegis-prometheus-service:9090
    isDefault: true
    uid: aegis-prometheus  
    editable: false